language: go

go:
  - 1.10.x
  - 1.11.x

env:
  - DEP_VERSION="0.5.1"

before_install:
  - curl -L -s "https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64" -o "$GOPATH/bin/dep"
  - chmod +x "$GOPATH/bin/dep"

install:
  - dep ensure -vendor-only

script:
  - go test -race -v ./...

cache:
  directories:
    - "$GOPATH/pkg/dep"
