[[constraint]]
  name = "github.com/fatih/camelcase"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/leboncoin/structs"
  version = "v1.0.1_lbc"

[[constraint]]
  name = "github.com/linkedin/goavro"
  version = "^2.7.2"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  source = "github.com/CountFenring/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
